# Generated by Django 5.1.4 on 2024-12-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCuisine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('image_url', models.CharField(max_length=128)),
                ('introduction', models.CharField(max_length=128)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'featured_cuisine',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('image_url', models.CharField(max_length=128)),
                ('introduction', models.CharField(max_length=128)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='TravelItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('status', models.BooleanField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'travel_item',
            },
        ),
        migrations.CreateModel(
            name='TravelItemDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('image_url', models.CharField(max_length=128)),
                ('ticket_price', models.CharField(max_length=10, null=True)),
                ('ticket_price_unit', models.CharField(max_length=12, null=True)),
                ('introduction', models.CharField(max_length=128)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'travel_item_detail',
            },
        ),
    ]
