# Generated by Django 5.1.4 on 2024-12-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredcuisine',
            name='image_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='travelitem',
            name='image_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='travelitemdetail',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
