# Generated by Django 5.1.4 on 2024-12-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_featuredcuisine_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelItemDetailRelImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('image_url', models.TextField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'travel_item_detail_rel_image',
            },
        ),
        migrations.RenameField(
            model_name='travelitemdetail',
            old_name='image_url',
            new_name='addr',
        ),
        migrations.AddField(
            model_name='travelitemdetail',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
