# Generated by Django 5.1.4 on 2024-12-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_travelitemdetailrelimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelitemdetail',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
